### ISSUE TITLE
GUDB readers do not work anymore?

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/sleepecg#108]
It looks like GUDB is not accessible anymore, at least not without registration:

https://berndporr.github.io/ECG-GUDB/

Our reader errors out, e.g.

```
404 Client Error: Not Found for url: https://berndporr.github.io/ECG-GUDB/experiment_data/subject_22/jogging/annotation_cables.tsv
```

We might need to use the API provided by the `ecg-gudb-database` package.

**Comment by berndporr** [comment]
```
bp1@bp1-Precision-WorkStation-T5400:~/sandbox/dataset_716/experiment_data/subject_22/jogging$ ls -la
total 46888
drwxr-xr-x 2 bp1 bp1     4096 Dec 10  2018 .
drwxr-xr-x 7 bp1 bp1     4096 Dec 10  2018 ..
-rw-r--r-- 1 bp1 bp1     1583 Dec 10  2018 annotation_cs.tsv
-rw-r--r-- 1 bp1 bp1  4560677 Dec 10  2018 ECG.tsv
-rw-r--r-- 1 bp1 bp1 43436757 Dec 10  2018 video.mp4
bp1@bp1-Precision-WorkStation-T5400:~/sandbox/dataset_716/experiment_data/subject_22/jogging$ 
```
There are a lot of jogging cases where there is no annotation. Been always like that. You need to check if there is an annotation.

**Comment by berndporr** [comment]
https://github.com/berndporr/ECG-GUDB/blob/master/usage_example.py#L80
see the usage example.

**Comment by berndporr** [comment]
Perhaps it's more a like "usage-regression". ;)

**Comment by cbrnr** [comment]
So are you saying that the direct download links are still available?

**Comment by berndporr** [comment]
Of course. Nothing has changed for ages.

**Comment by berndporr** [comment]
I can only repeat: look at the usage examples before you fire of unsubstantiated claims.

**Comment by cbrnr** [comment]
Why are you so aggressive? I'm not making any claims, just asking questions.

**Comment by berndporr** [comment]
Because people will read the heading of this issue and assume something is wrong with GUDB. How would you feel if I file a similar issue here for example "sleepecg seems to be no longer working". I'm sure I'll find a snag when trying to install it. What you are doing is trying to put the GUDB in disrepute which is not on.

**Comment by cbrnr** [comment]
Alright, this is getting ridiculous. Unless you apologize I am going to report this behavior. Did you even notice that this is my repository and not yours?

**Comment by berndporr** [comment]
I have deleted my previous comment as it could have been misunderstood. Apologies for that.
Can I ask you to delete this issue as it simply contains a falsehood.
Thanks, B

**Comment by cbrnr** [comment]
OK. This is an issue with our package, not with GUDB. I ran some tests and got the errors. I will close the issue once we have fixed it. I have renamed the issue to make it clear that this is *not* about GUDB.

**Comment by hofaflo** [comment]
This has always been the case, `read_gudb` skips the records without annotations and [prints the HTTPError](https://github.com/cbrnr/sleepecg/blob/main/sleepecg/io/ecg_readers.py#L250-L251) raised because the file isn't available - which is admittedly not the most transparent way of handling this situation.

**Comment by cbrnr** [comment]
OK cool, we should probably change that.
