### ISSUE TITLE
Migrating to Python 3.9

### ISSUE THREAD

**Issue by hofaflo** [cbrnr/sleepecg#16]
When we require [Python 3.9](https://docs.python.org/3/whatsnew/3.9.html) in the future, we can make use of the following updates:

- [ ] [Type hinting generics](https://www.python.org/dev/peps/pep-0585/) (in every function expecting or returning e.g. a list, dict or tuple).

If you encounter situations for which Python 3.9 would allow a more elegant solution, please note them here.

**Comment by hofaflo** [comment]
Since we started using `from __future__ import annotations` in #105, there isn't really much left to do here. I think we can close this issue - and if a situation arises where supporting 3.8 actually makes something difficult we can discuss again, WDYT @cbrnr?

**Comment by cbrnr** [comment]
We could leave it open though to remind us to remove the future import once we move to 3.9. Or would we get some kind of info message from some linter?

**Comment by hofaflo** [comment]
I was hoping mypy would say something, but apparently it doesn't :/ So yes, let's leave it open.

**Comment by cbrnr** [comment]
When do you think we should drop support for Python 3.8? I would argue that supporting the last three versions is more than sufficient. This would mean 3.9, 3.10, and 3.11 – but of course only if all features work on all versions. Therefore, I suggest to drop support for 3.8 once Numba and Tensorflow are compatible with 3.11.

**Comment by hofaflo** [comment]
I don't have a strong opinion on this, though I don't see why we shouldn't support 3.8 as long as it doesn't hinder development :thinking:

**Comment by cbrnr** [comment]
True, but it's good to have a set of rules in place. If we take https://devguide.python.org/versions/ as a guide, we could keep 3.8 around until October 2024. But I don't think we have to. Fewer supported versions means fewer maintenance burden. I don't know. I thought it would be nice to have a rule instead of deciding ad-hoc "this version is already too old so let's drop support for it".

**Comment by hofaflo** [comment]
Okay, I'm fine with "support the latest 3 python versions for which all features work"

**Comment by cbrnr** [comment]
We only need to wait for Numba and Tensorflow to support Python 3.11, then we can drop Python 3.8:

https://github.com/numba/numba/issues/8304
https://github.com/tensorflow/tensorflow/issues/58032

**Comment by EwoutH** [comment]
The NumPy version support standard ([NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)) could be an interesting one to follow. It uses a 42 month support windows (3.5 years, instead of the regular 5 years), which means that on Apr 14, 2023, Python 3.8 is dropped an 3.9 required, and on Apr 05, 2024, Python 3.9 will be dropped and 3.10 required.

**Comment by cbrnr** [comment]
Thanks, this sounds good! Not having to invent yet another support schedule and just following something that a large project has alread put a lot of thought in is a very good idea!

**Comment by cbrnr** [comment]
I'm closing this, because we are already using what is proposed in the first comment (type hinting generics). This works because of the `__future__` imports, which we can only drop starting with Python 3.10.
