### ISSUE TITLE
switch from relative to absolute imports?

### ISSUE THREAD

**Issue by tompollard** [cbrnr/sleepecg#164]
This is a quick issue relating to the JOSS review comments at: https://github.com/openjournals/joss-reviews/issues/5411#issuecomment-1548163405

Absolute imports seem to be generally preferred by Python developers (https://peps.python.org/pep-0008/#imports). sleepecg uses relative imports in places (e.g. from .physionet import _list_physionet). Is this intentional? If not, perhaps switch to absolute imports at some point?

**Comment by cbrnr** [comment]
This is a good point. I have been using relative imports in my packages out of habit, with the main reason being that it makes some imports shorter. But you are right, I think it would definitely be worthwile to check if switching to absolute imports would make anything more complex. If not, I think we should go for it. I'll link the corresponding PR so that we can decide if it's worth it or not!
